
package com.example.testtaskjsontoxml.service.newgen;

import jakarta.xml.ws.*;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
//import javax.xml.ws.Service;
//import javax.xml.ws.WebEndpoint;
//import javax.xml.ws.WebServiceClient;
//import javax.xml.ws.WebServiceException;
//import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "serviceName", targetNamespace = "http://www.example.com/springsoap/gen", wsdlLocation = "http://localhost:8181/ws")
public class ServiceName
    extends Service
{

    private final static URL SERVICENAME_WSDL_LOCATION;
    private final static WebServiceException SERVICENAME_EXCEPTION;
    private final static QName SERVICENAME_QNAME = new QName("http://www.example.com/springsoap/gen", "ClientInterfaceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8181/ws/client.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICENAME_WSDL_LOCATION = url;
        SERVICENAME_EXCEPTION = e;
    }

    public ServiceName() {
        super(__getWsdlLocation(), SERVICENAME_QNAME);
    }

    public ServiceName(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICENAME_QNAME, features);
    }

    public ServiceName(URL wsdlLocation) {
        super(wsdlLocation, SERVICENAME_QNAME);
    }

    public ServiceName(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICENAME_QNAME, features);
    }

    public ServiceName(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceName(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClientInterface
     */
    @WebEndpoint(name = "portName")
    public ClientInterface getPortName() {
        return super.getPort(new QName("http://www.example.com/springsoap/gen", "ClientInterfaceSoap11"), ClientInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns ClientInterface
     */
    @WebEndpoint(name = "portName")
    public ClientInterface getPortName(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.com/springsoap/gen", "ClientInterfaceSoap11"), ClientInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICENAME_EXCEPTION!= null) {
            throw SERVICENAME_EXCEPTION;
        }
        return SERVICENAME_WSDL_LOCATION;
    }

}
